// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBInCsIm4Nf-WEkvqSzNRgeQ1Yr8xUiRI',
    appId: '1:62539984442:web:cadf7111dbdb2fa312cf03',
    messagingSenderId: '62539984442',
    projectId: 'aquajex-806db',
    authDomain: 'aquajex-806db.firebaseapp.com',
    storageBucket: 'aquajex-806db.firebasestorage.app',
    measurementId: 'G-S0Q5CYNK82',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBInCsIm4Nf-WEkvqSzNRgeQ1Yr8xUiRI',
    appId: '1:62539984442:web:54efd4434b37b80b12cf03',
    messagingSenderId: '62539984442',
    projectId: 'aquajex-806db',
    authDomain: 'aquajex-806db.firebaseapp.com',
    storageBucket: 'aquajex-806db.firebasestorage.app',
    measurementId: 'G-CZJNL01DS7',
  );
}
